### ISSUE TITLE
No module named spatial_pooler

### ISSUE THREAD

**Issue by aqibmumtaz** [numenta/nupic.vision#61]
Im able to successfully install nupic.vision following instructions https://github.com/numenta/nupic.vision/issues/60

Now when I try to run vision -> ocr -> demo.py it given me following error 

```
Traceback (most recent call last):
  File "/Users/aqibmumtaz/Aqib Mumtaz/Server Dev/python/Nupic/nupic.vision-master/src/nupic/vision/ocr/demo.py", line 31, in <module>
    from nupic.algorithms.spatial_pooler import SpatialPooler
ImportError: No module named spatial_pooler

```
 
Please note that I have already installed nupic dependencies as followings :

```
nupic | 0.6.0 | 1.0.3
nupic.bindings | 0.6.0 | 1.0.2
nupic.vision | 0.1.0 |  

```

Could you please assist me how can I fix this error?

I suspected its due to nupic 0.6 older installed version which is missing 'spatial_pooler'.

So, I have then tried updating nupic and nupic.bindings to latest 1.0.x version then running the code again. but its started giving me following errors now : 

```
Traceback (most recent call last):
  File "/Users/aqibmumtaz/Aqib Mumtaz/Server Dev/python/Nupic/nupic.vision-master/src/nupic/vision/ocr/demo.py", line 36, in <module>
    from nupic.vision.ocr.classifiers import exactMatch
  File "/Users/aqibmumtaz/pc_env2.7/lib/python2.7/site-packages/nupic/vision/ocr/classifiers.py", line 27, in <module>
    from nupic.algorithms.KNNClassifier import KNNClassifier
ImportError: No module named KNNClassifier

```

**Is there a way I can test any demo project from nupic.vision? I m interested in anomaly detections on Videos let me know how can I do that ??**

Thanks

**Comment by rhyolight** [comment]
I'm not sure that nupic.vision was updated for NuPIC 1.0. It was probably only updated to work with the latest nupic.core. @scottpurdy is that the case?

If so, I will update this issue to make nupic.vision work with NuPIC 1.0+

**Comment by scottpurdy** [comment]
It is very likely that nupic.vision has a lot of broken code in it. The mnist SP-only example is the main thing we have kept running. Not sure the status of the repo.

**Comment by aqibmumtaz** [comment]
Thanks guys for your feedback. please keep me posted when issue is fixed.

**Comment by rhyolight** [comment]
@aqibmumtaz I don't plan on working on this for awhile, but I will certainly post here when it is done.

**Comment by kaikun213** [comment]
Just in case someone wants to get saccade_experiment running.
It worked for me with the following old commits:
htmresearch: de8539e643c898666f2dbd37ec7f79abfab4506b
htmresearch-core: 8c0b19866533035662a247ec707ac66ce242b5be
