### ISSUE TITLE
Install via Docker on Windows 10 fails

### ISSUE THREAD

**Issue by Garfield2013** [numenta/nupic.vision#63]
I get this error when I try to install via Docker (in the end it says Python 3.5 is needed? But Nupic only runs with Python 2.7?) - How do I fix this?

PS C:\Users\TB\Downloads\nupic.vision-master\nupic.vision-master> docker build -t nupic.vision .
Sending build context to Docker daemon  23.51MB
Step 1/12 : FROM python:2.7
 ---> b707c2244b7d
Step 2/12 : COPY requirements.txt /nta/nupic.vision/requirements.txt
 ---> Using cache
 ---> 0005044a05bd
Step 3/12 : RUN pip install -r /nta/nupic.vision/requirements.txt
 ---> Running in 989b989cebdc
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pillow==2.3.0 (from -r /nta/nupic.vision/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/25/b7/b9da63e4d7fcf6efb04c001df1a4d035dbeeb6846d299696a6fec354531f/Pillow-2.3.0.zip (2.4MB)
Collecting enum34==1.0.4 (from -r /nta/nupic.vision/requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/72/c9/3c640a9cd54a731f3c54d97515b06aae6f6d16a5878a632dbfa9ffe5e663/enum34-1.0.4.tar.gz
Collecting nupic==1.0.5 (from -r /nta/nupic.vision/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/44/fa/4b1a4f0c3a89b661241f668010dbc3133b700aa680cc575a6ffa4a3dba22/nupic-1.0.5-py2-none-any.whl (4.8MB)
Collecting htmresearch==0.0.2 (from -r /nta/nupic.vision/requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/ca/84/f5ed58b86a7f00a88c0c4c00e6002d76ff3a6437d35b1f5ca0a94e14d927/htmresearch-0.0.2-py2-none-any.whl (277kB)
Collecting asteval==0.9.1 (from nupic==1.0.5->-r /nta/nupic.vision/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/63/26/c126345158a1c3d5c0b2c5447bc222f1380ff023eaed4d33edafef9eb1bf/asteval-0.9.1.tar.gz
Collecting unittest2==0.5.1 (from nupic==1.0.5->-r /nta/nupic.vision/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/86/e8/f31a7c9a3b471f6125abc8addd37c17760e00affb45d6db088394a360086/unittest2-0.5.1.tar.gz (62kB)
Collecting pytest-xdist==1.16.0 (from nupic==1.0.5->-r /nta/nupic.vision/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/0d/d0/58cacddb34f35dd3d447525061e431b00d842eef72d585cc1c9a97abec90/pytest-xdist-1.16.0.tar.gz (88kB)
Collecting pyproj==1.9.3 (from nupic==1.0.5->-r /nta/nupic.vision/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/f9/7f/ee337f570e4c3ef4593709dcb63e813c359184ede249c4f79b761186bd08/pyproj-1.9.3.tar.gz (2.7MB)
Collecting PyMySQL==0.6.2 (from nupic==1.0.5->-r /nta/nupic.vision/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/04/65/c84eee72dcbf19d8050cf65157a15f68e0989620a00bf0b2a55a1a20b4cd/PyMySQL-0.6.2-py2.py3-none-any.whl (63kB)
Collecting ordereddict==1.1 (from nupic==1.0.5->-r /nta/nupic.vision/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/53/25/ef88e8e45db141faa9598fbf7ad0062df8f50f881a36ed6a0073e1572126/ordereddict-1.1.tar.gz
Collecting pytest==3.0.7 (from nupic==1.0.5->-r /nta/nupic.vision/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/8e/81/40a4b62b1d15441c282db485f8f08c7c38edab9ffe750a31d77805cd5f6a/pytest-3.0.7-py2.py3-none-any.whl (172kB)
Collecting pycapnp==0.6.3; platform_system == "Linux" or platform_system == "Darwin" (from nupic==1.0.5->-r /nta/nupic.vision/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/73/5e/f9e4369639883c1efc1c1729e51ed65b5acdadf3445cfa800b1db66d5856/pycapnp-0.6.3.tar.gz (455kB)
Collecting psutil==1.0.1 (from nupic==1.0.5->-r /nta/nupic.vision/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/94/50/7c9e94cf6cdbf4e4e41d2e318094c2b0d58d3bb9196017fb6e4897adf277/psutil-1.0.1.tar.gz (156kB)
Collecting DBUtils==1.1 (from nupic==1.0.5->-r /nta/nupic.vision/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/65/65/89afee016aca7fbb5c1642e6ef3864d80af808dc5efa7367b328093eece9/DBUtils-1.1.tar.gz (109kB)
Collecting coverage==3.7.1 (from nupic==1.0.5->-r /nta/nupic.vision/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/09/4f/89b06c7fdc09687bca507dc411c342556ef9c5a3b26756137a4878ff19bf/coverage-3.7.1.tar.gz (284kB)
Collecting nupic.bindings==1.0.6 (from nupic==1.0.5->-r /nta/nupic.vision/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/71/8f/c9604b045646bca155779373fb851b600994fe94bf452d1ae43d0383fa00/nupic.bindings-1.0.6-cp27-cp27mu-manylinux1_x86_64.whl (4.1MB)
Collecting python-dateutil==2.1 (from nupic==1.0.5->-r /nta/nupic.vision/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/65/52/9c18dac21f174ad31b65e22d24297864a954e6fe65876eba3f5773d2da43/python-dateutil-2.1.tar.gz (152kB)
Collecting mock==1.0.1 (from nupic==1.0.5->-r /nta/nupic.vision/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/a2/52/7edcd94f0afb721a2d559a5b9aae8af4f8f2c79bc63fdbe8a8a6c9b23bbe/mock-1.0.1.tar.gz (818kB)
Collecting PyYAML==3.10 (from nupic==1.0.5->-r /nta/nupic.vision/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/00/17/3b822893a1789a025d3f676a381338516a8f65e686d915b0834ecc9b4979/PyYAML-3.10.tar.gz (241kB)
Collecting numpy==1.12.1 (from nupic==1.0.5->-r /nta/nupic.vision/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/f9/d5/f24f86b51298f171826a398efdd64b5214b687a28a2f05ff736b1505b1b2/numpy-1.12.1-cp27-cp27mu-manylinux1_x86_64.whl (16.5MB)
Collecting validictory==0.9.1 (from nupic==1.0.5->-r /nta/nupic.vision/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/aa/57/2b29d7886815854a648ad3503e616f2164a78467fdd603fa8adf0dee028e/validictory-0.9.1.tar.gz
Collecting pytest-cov==2.5.0 (from nupic==1.0.5->-r /nta/nupic.vision/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/35/02/fb4e0f9b0423f26214eea9fd07f9fa0758ecf2bea0b8d8e61667a91e6298/pytest_cov-2.5.0-py2.py3-none-any.whl
Collecting prettytable==0.7.2 (from nupic==1.0.5->-r /nta/nupic.vision/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/ef/30/4b0746848746ed5941f052479e7c23d2b56d174b82f4fd34a25e389831f5/prettytable-0.7.2.tar.bz2
Collecting pyqtgraph==0.10.0 (from htmresearch==0.0.2->-r /nta/nupic.vision/requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/cd/ad/307e0280df5c19986c4206d138ec3a8954afc722cea991f4adb4a16337d9/pyqtgraph-0.10.0.tar.gz (1.5MB)
Collecting tqdm==4.8.4 (from htmresearch==0.0.2->-r /nta/nupic.vision/requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/3a/c0/2653e9a90aef358da8880980c155218791f79b9a1d479a9a00f88ac42aac/tqdm-4.8.4-py2.py3-none-any.whl
Collecting matplotlib==2.1.0 (from htmresearch==0.0.2->-r /nta/nupic.vision/requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/89/b2/41ae0d5922a8018c1f506ef9b9363fca60326c8b24241b13ecaf80fede47/matplotlib-2.1.0-cp27-cp27mu-manylinux1_x86_64.whl (14.9MB)
Collecting simplejson==2.6.2 (from htmresearch==0.0.2->-r /nta/nupic.vision/requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/a0/21/6600c517d3208d591426ab5da3fd0aaaa278acb820e2949592cd33722057/simplejson-2.6.2.tar.gz (53kB)
Collecting plyfile==0.5 (from htmresearch==0.0.2->-r /nta/nupic.vision/requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/51/20/cd2d20e6936c31587738f05ec7f96fceeed8e6eb3732f541f760267e8cdb/plyfile-0.5.tar.gz
Collecting gensim==3.0.0 (from htmresearch==0.0.2->-r /nta/nupic.vision/requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/e5/c8/613eda948a786370e05e0f96817eb7d60a30fc15b9796c4d46b4fc839574/gensim-3.0.0.tar.gz (59.5MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vxtUx7/gensim/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vxtUx7/gensim/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-vxtUx7/gensim/
    Complete output (51 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vxtUx7/gensim/setup.py", line 301, in <module>
        include_package_data=True,
      File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 719, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/local/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-WOl_WD/numpy-1.17.2/setup.py", line 31, in <module>

    RuntimeError: Python version >= 3.5 required.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c pip install -r /nta/nupic.vision/requirements.txt' returned a non-zero code: 1

**Comment by rhyolight** [comment]
I think this is an issue because the nupic docker image is currently broken. @lscheinkman was going to work on it soon. I'll let you know when it is fixed.

**Comment by Garfield2013** [comment]
ooh! I see...Yes - that would be great! :)
I guess you should mark this repo as broken for the time being...I personally have been struggling for days with it so far :(

**Comment by Garfield2013** [comment]
Btw - does any other Numenta/Nupic repo exists which has an example of the classic 0-9 MNIST?

**Comment by rhyolight** [comment]
> I guess you should mark this repo as broken

https://github.com/numenta/nupic.vision/pull/64

> what is the ETA for fixing this repo?

The NuPIC docker image will definitely be done by Jan 2020.
